services:
  dozzle:
    image: amir20/dozzle:latest@sha256:a70238909232f61ebcfdc4617200cb32872be481a51d8c65cc56c4f261ba66ca
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    mem_limit: 256m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "${DOZZLE_BIND_ADDRESS:-127.0.0.1}:${DOZZLE_PORT:-8188}:8080"
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle-data:/data

volumes:
  dozzle-data:
