allow.auto.create.topics                  = true
auto.commit.interval.ms                   = 5000
auto.offset.reset                         = earliest
bootstrap.servers                         = localhost:9092
client.id                                 = kafman-consumer
enable.auto.commit                        = false
enable.partition.eof                      = false
fetch.max.bytes                           = 52428800
fetch.min.bytes                           = 1
fetch.wait.max.ms                         = 500
group.id                                  = kafman-consumer
heartbeat.interval.ms                     = 3000
isolation.level                           = read_committed
max.partition.fetch.bytes                 = 1048576
max.poll.interval.ms                      = 300000
max.poll.records                          = 500
reconnect.backoff.max.ms                  = 10000
reconnect.backoff.ms                      = 100
session.timeout.ms                        = 45000
sasl.mechanism                            = PLAIN
sasl.password                             = password
sasl.username                             = username
security.protocol                         = PLAINTEXT
ssl.ca.location                           = /path/to/ca.pem
ssl.certificate.location                  = /path/to/certificate.pem
ssl.key.location                          = /path/to/key.pem
ssl.key.password                          = password
