acks                                      = -1
batch.num.messages                        = 10000
batch.size                                = 1000000
bootstrap.servers                         = localhost:9092
client.id                                 = kafman-producer
compression.type                          = none
delivery.timeout.ms                       = 120000
enable.idempotence                        = true
linger.ms                                 = 5
max.in.flight.requests.per.connection     = 5
message.max.bytes                         = 1000000
message.timeout.ms                        = 300000
queue.buffering.max.kbytes                = 1048576
queue.buffering.max.messages              = 100000
reconnect.backoff.max.ms                  = 10000
reconnect.backoff.ms                      = 100
request.timeout.ms                        = 30000
retries                                   = 2147483647
retry.backoff.ms                          = 100
sasl.mechanism                            = PLAIN
sasl.password                             = password
sasl.username                             = username
security.protocol                         = PLAINTEXT
ssl.ca.location                           = /path/to/ca.pem
ssl.certificate.location                  = /path/to/certificate.pem
ssl.key.location                          = /path/to/key.pem
ssl.key.password                          = password
