services:
  kafka-broker:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:7.9.8
    hostname: kafka_broker
    restart: unless-stopped
    mem_limit: 1g
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "nc -vz localhost 9092" ]
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 60s
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "127.0.0.1:9092:29092"
      - "127.0.0.1:9093:9093"
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"
      KAFKA_BROKER_ID: 1
      KAFKA_JMX_PORT: 9093
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka:rw
    networks:
      - esnet

volumes:
  kafka-data:
