services:

  jenkins:
    image: jenkins/jenkins:lts@sha256:a660310e39ade10631f774bacd5219de767dfd08947ea5c32a739b5e5bb382c1
    container_name: jenkins
    hostname: jenkins
    restart: unless-stopped
    mem_limit: 2g
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "--max-time", "3", "http://localhost:8080/login" ]
      timeout: 60s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:9001:8080"
      - "127.0.0.1:50003:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - esnet

networks:
  esnet:

volumes:
  jenkins-data:
